---

- name: Clean up prior run
  shell: rm -rf roles/build_admin_client/files/docker/app/*
  delegate_to: 127.0.0.1

- name: Pull Midwife-EMR Repo
  shell: git archive --remote=https://github.com/LightSys/midwife-EMR master |tar -xf -
  args:
    chdir: roles/build_admin_client/files/docker/app
  delegate_to: 127.0.0.1

- name: Build admin client image
  shell: docker build -f Dockerfile -t build_admin_client:latest .
  args:
    chdir: roles/build_admin_client/files/docker
  delegate_to: 127.0.0.1

- name: Clear any prior deliverables
  shell: rm *
  args:
    chdir: roles/build_admin_client/files/docker/dist
  delegate_to: 127.0.0.1

- name: Run admin client image to produce deliverables
  shell: docker container run --rm -v $(pwd)/dist:/opt/dist build_admin_client:latest
  args:
    chdir: roles/build_admin_client/files/docker
  delegate_to: 127.0.0.1
