---

- name: Download Nodejs
  get_url:
    url: "https://nodejs.org/dist/v6.4.0/node-v{{ nodejs_version }}-linux-armv7l.tar.gz"
    dest: "{{ download_dir }}/node-v{{ nodejs_version }}-linux-armv7l.tar.gz"

- name: Install Nodejs
  # Note: Using tar instead of the unarchive module because don't see that the
  # unarchive module can strip components.
  shell: /bin/tar -xzf {{ download_dir }}/node-v{{ nodejs_version }}-linux-armv7l.tar.gz --strip-components=1 --group=root --no-same-owner -C /usr/local/
  args:
    creates: /usr/local/bin/node

