---

- name: Create download directory
  file: path="{{ download_dir }}" state=directory mode=0700

- name: Set hostname
  hostname: name="{{ hostname }}"

- name: Set hostname in /etc/hosts too
  lineinfile:
    dest: /etc/hosts
    regexp: ^127\.0\.0\.1.*{{ hostname }}$
    line: "127.0.0.1 {{ hostname }}"
    state: present

- name: Install shmig for migrations
  get_url:
    url: https://raw.githubusercontent.com/mbucc/shmig/aff54e03d13f8f95b422cf898505490a56152a4a/shmig
    dest: /usr/local/bin
    mode: u=rwx,go=rx
    group: root
    owner: root

## Adapted from: https://stackoverflow.com/a/38510313
- name: remove reference to non-existent xconsole from rsyslog configuration file
  replace:
    dest: /etc/rsyslog.d/50-default.conf
    regexp: "\\|/dev/xconsole"
    replace: "|/dev/null"
    backup: yes
