---

- name: Add the required password to automysqlbackup cron job
  template:
    src: roles/backups/files/automysqlbackup.j2
    dest: /etc/cron.daily/automysqlbackup
    mode: "u=rw,go=r"
    owner: root
    group: root

- name: create mount point for SDcard backup
  file:
    path: /backups
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go="

- name: turn off chattr
  command: chattr -i /etc/fstab

- name: adjust fstab to handle microSD card
  blockinfile:
    dest: /etc/fstab
    marker: "# {mark} ANSIBLE - role: backups, adjust fstab to handle microSD card"
    block: |
      # Note that this file is protected with chattr +i because the OS
      # seems to get confused about the purpose of the SD Card and it
      # modifies fstab so that the SD Card is mounted at /media/boot.
      # It does this by replacing the UUID with the SD Card's partition
      # 1 UUID.
      #
      # To modify this file, type this as root
      #     chattr -i /etc/fstab
      # After making changes, prevent future changes with
      #    chattr +i /etc/fstab
      #
      # UUID is not used here because the SD Card may
      # be swapped out with a different card at times.
      /dev/mmcblk1p1 /backups exfat defaults,nofail
    insertafter: EOF

- name: turn on chattr
  command: chattr +i /etc/fstab

- name: Create a place on primary drive for staging backups (non-MySQL)
  file:
    dest: /var/lib/backups/files
    state: directory
    recurse: yes

- name: Copy /etc to backups
  cron:
    name: "Copy /etc to backups"
    minute: "15"
    hour: "18"
    job: "/bin/tar -czf /var/lib/backups/files/etc.tar.gz /etc"
    user: root
    cron_file: etc_to_backups

- name: Copy latest version in use of Midwife-EMR to backups
  cron:
    name: "Copy latest version in use of Midwife-EMR to backups"
    minute: "20"
    hour: "18"
    job: "/bin/tar -czf /var/lib/backups/files/midwife-emr.tar.gz /srv/midwife-emr/midwife-emr/"
    user: root
    cron_file: midwife-emr_to_backups

- name: Copy crontab to backups
  cron:
    name: "Copy crontab to backups"
    minute: "25"
    hour: "18"
    job: "/bin/tar -czf /var/lib/backups/files/cron-daily.tar.gz /etc/cron.daily"
    user: root
    cron_file: cron_to_backups

- name: Copy non-MySQL backups files to secondary drive
  cron:
    name: "Copy non-MySQL backups files to secondary drive"
    minute: "0"
    hour: "19"
    job: "/bin/cp -r /var/lib/backups /"
    user: root
    cron_file: files_to_sdcard

- name: Copy MySQL backup files to secondary drive
  cron:
    name: "Copy MySQL backups files to secondary drive"
    minute: "5"
    hour: "19"
    job: "/bin/cp -r /var/lib/automysqlbackup /backups/"
    user: root
    cron_file: mysql_to_sdcard
