---

- name: remove the cron.daily file for automysqlbackup
  file:
    path: /etc/cron.daily/automysqlbackup
    state: absent

### ==========================================================================
### Note: we are not using the Ansible cron module due to Ansible issue #4777.
### https://github.com/ansible/ansible-modules-core/pull/4777
### ==========================================================================

- name: add automysqlbackup to cron file
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: backups, add automysqlbackup to cron file"
    block: |
      0 18 * * * root /usr/sbin/automysqlbackup >/dev/null 2>&1
    insertafter: EOF
    state: present

- name: create mount point for SDcard backup
  file:
    path: /backups
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go="

- name: turn off chattr
  command: chattr -i /etc/fstab

- name: adjust fstab to handle microSD card
  blockinfile:
    dest: /etc/fstab
    marker: "# {mark} ANSIBLE - role: backups, adjust fstab to handle microSD card"
    block: |
      # Note that this file is protected with chattr +i because the OS
      # seems to get confused about the purpose of the SD Card and it
      # modifies fstab so that the SD Card is mounted at /media/boot.
      # It does this by replacing the UUID with the SD Card's partition
      # 1 UUID.
      #
      # To modify this file, type this as root
      #     chattr -i /etc/fstab
      # After making changes, prevent future changes with
      #    chattr +i /etc/fstab
      #
      # UUID is not used here because the SD Card may
      # be swapped out with a different card at times.
      /dev/mmcblk1p1 /backups vfat defaults,nobootwait
    insertafter: EOF

- name: turn on chattr
  command: chattr +i /etc/fstab

- name: Create a place on primary drive for staging backups (non-MySQL)
  file:
    dest: /var/lib/backups/files
    state: directory
    recurse: yes

- name: Copy /etc to backups
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: backups, Copy /etc to backups"
    block: |
      15 18 * * * root /bin/tar -czf /var/lib/backups/files/etc.tar.gz /etc >/dev/null 2>&1
    insertafter: EOF
    state: present

- name: Copy latest version in use of Midwife-EMR to backups
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: backups, Copy latest version in use of Midwife-EMR to backups"
    block: |
      20 18 * * * root /bin/tar -czf /var/lib/backups/files/midwife-emr.tar.gz /srv/midwife-emr/midwife-emr/ >/dev/null 2>&1
    insertafter: EOF
    state: present

- name: Copy crontab to backups
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: backups, Copy crontab to backups"
    block: |
      25 18 * * * root cat /etc/crontab >/var/lib/backups/files/crontab.txt
    insertafter: EOF
    state: present

- name: Copy non-MySQL backups files to secondary drive
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: backups, Copy non-MySQL backups files to secondary drive"
    block: |
      0 19 * * * root /bin/cp -r /var/lib/backups /
    insertafter: EOF
    state: present

- name: Copy MySQL backup files to secondary drive
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: backups, Copy MySQL backup files to secondary drive"
    block: |
      5 19 * * * root /bin/cp -r /var/lib/automysqlbackup/* /backups/automysqlbackup
    insertafter: EOF
    state: present

