---

- name: Install Midwife-EMR-Internal
  git:
    repo: https://github.com/kbsymanz/midwife-emr-internal-docs
    dest: "{{ download_dir }}/midwife-emr-internal-docs"

- name: Install npm requirements
  npm:
    path: "{{ download_dir }}/midwife-emr-internal-docs"
    production: yes

- name: Create the deployment directory
  file:
    state: directory
    dest: "{{ midwife_emr_internal_docs_deploy_dir }}"
    owner: "midwifeemr"
    group: "midwifeemr"
    mode: "ugo=rx"

- name: Deploy the midwife-emr-internal site
  shell: "{{ download_dir }}/midwife-emr-internal-docs/deploy.sh {{ midwife_emr_internal_docs_deploy_dir }}"

- name: Install the Nginx configuration file
  copy:
    src: ../files/midwife-emr-internal-docs
    dest: /etc/nginx/sites-available/midwife-emr-internal-docs
    owner: root
    group: root
    mode: "u=rw,go=r"

- name: Enable the internal docs configuration
  command: ln -fs /etc/nginx/sites-available/midwife-emr-internal-docs /etc/nginx/sites-enabled/midwife-emr-internal-docs


- name: Create the directory for the repo update script
  file:
    state: directory
    dest: /root/bin
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Install the repo update script
  copy:
    src: ../files/update-midwife-emr-internal-docs
    dest: /root/bin/update-midwife-emr-internal-docs
    owner: root
    group: root
    mode: "u=rwx,go="

### ==========================================================================
### Note: we are not using the Ansible cron module due to Ansible issue #4777.
### https://github.com/ansible/ansible-modules-core/pull/4777
### ==========================================================================

- name: Install the cron job to run the update script
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE - role: midwife-emr-internal, Install the cron job to run the update script"
    block: |
      0 5 * * * root /root/bin/update-midwife-emr-internal-docs >/dev/null 2>&1
    insertafter: EOF
    state: present

