---

- name: Install Midwife-EMR-Internal
  git:
    repo: https://github.com/kbsymanz/midwife-emr-internal-docs
    dest: "{{ download_dir }}/midwife-emr-internal-docs"

- name: Install npm requirements
  npm:
    path: "{{ download_dir }}/midwife-emr-internal-docs"
    production: yes

- name: Create the deployment directory
  file:
    state: directory
    dest: "{{ midwife_emr_internal_docs_deploy_dir }}"
    owner: "midwifeemr"
    group: "midwifeemr"
    mode: "ugo=rx"

- name: Deploy the midwife-emr-internal site
  shell: "{{ download_dir }}/midwife-emr-internal-docs/deploy.sh {{ midwife_emr_internal_docs_deploy_dir }}"

- name: Install the Nginx configuration file
  copy:
    src: ../files/midwife-emr-internal-docs
    dest: /etc/nginx/sites-available/midwife-emr-internal-docs
    owner: root
    group: root
    mode: "u=rw,go=r"

- name: Enable the internal docs configuration
  command: ln -fs /etc/nginx/sites-available/midwife-emr-internal-docs /etc/nginx/sites-enabled/midwife-emr-internal-docs

