---

- name: Install Midwife-EMR-Internal
  git:
    repo: https://github.com/lightsys/midwife-emr-internal-docs
    dest: "{{ download_dir }}/midwife-emr-internal-docs"

- name: Install npm requirements
  npm:
    path: "{{ download_dir }}/midwife-emr-internal-docs"
    production: yes

- name: Create the deployment directory
  file:
    state: directory
    dest: "{{ midwife_emr_internal_docs_deploy_dir }}"
    owner: "midwifeemr"
    group: "midwifeemr"
    mode: "ugo=rx"

- name: Deploy the midwife-emr-internal site
  shell: "{{ download_dir }}/midwife-emr-internal-docs/deploy.sh {{ midwife_emr_internal_docs_deploy_dir }}"

# Note: the manage-midwife-emr-tls script generates the Nginx config file,
# installs, and activates it.

- name: Create the directory for the repo update script
  file:
    state: directory
    dest: /root/bin
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Install the repo update script
  copy:
    src: roles/midwife-emr-internal/files/update-midwife-emr-internal-docs
    dest: /root/bin/update-midwife-emr-internal-docs
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Install the cron job to run the update script
  cron:
    name: "Install the cron job to run the update script"
    minute: "5"
    hour: "0"
    job: "/root/bin/update-midwife-emr-internal-docs"
    user: root
    cron_file: update-midwife-emr-internal-docs
