---
- name: Generate locales that we want
  command: /usr/sbin/locale-gen en_US

- name: Generate more locales that we want
  command: /usr/sbin/locale-gen en_US.UTF-8

- name: Set default locale
  debconf: name=locales question='locales/default_environment_locale' value="{{ locale }}" vtype='select'

- name: Get timezone
  command: /usr/bin/timedatectl status
  register: timedatectl_contents

- name: Set timezone if needed
  command: /usr/bin/timedatectl set-timezone {{ timezone }}
  when: timedatectl_contents.stdout.find("Time zone") == -1
