---
- name: Configure the shutdown button
  copy:
    src: ../files/powerbtn.sh
    dest: /etc/acpi/powerbtn.sh
    mode: "u=rwx,go=rx"
    owner: root
    group: root
  register: was_shutdown_installed

- name: restart acpid service
  service:
    name: acpid
    enabled: yes
    state: restarted
  when: was_shutdown_installed.changed

- name: Schedule reboots to keep the OS running well
  cron:
    name: "Schedule reboots"
    minute: "0"
    hour: "3"
    day: "*"
    month: "*"
    weekday: "0,3"
    state: present
    job: "/sbin/shutdown -r now"
