---

- name: Schedule reboots to keep the OS running well
  cron:
    name: "Schedule reboots to keep the OS running well"
    minute: "3"
    hour: "0"
    weekday: "0,3"
    job: "/sbin/shutdown -r now"
    user: root
    cron_file: reboot-midwife-emr
