---

- name: Create the bin directory for the support user
  file:
    path: "/home/{{ support_user }}/bin"
    state: directory
    owner: "{{ support_user }}"
    group: "users"
    mode: "u=rwx,go="

- name: Add a myip alias for the support user
  lineinfile:
    create: yes
    dest: "/home/{{ support_user }}/.bash_aliases"
    owner: "{{ support_user }}"
    group: users
    mode: "u=rw,go=r"
    state: present
    regexp: "^alias myip"
    line: "alias myip='curl -s myip.dnsomatic.com|sed -e \"s/$/\\n/\"'"

- name: Add a followlog alias for the support user
  lineinfile:
    create: yes
    dest: "/home/{{ support_user }}/.bash_aliases"
    owner: "{{ support_user }}"
    group: users
    mode: "u=rw,go=r"
    state: present
    regexp: "^alias followlog"
    line: "alias followlog='sudo tail -f /var/log/upstart/midwife-emr.log'"

- name: Add midwife-emr group
  group: name=midwifeemr state=present

- name: Add midwife-emr user
  user:
    name=midwifeemr
    password="{{ midwifeemr_user_password }}"
    comment="Midwife-EMR service user"
    group=midwifeemr
    state=present
    createhome=yes
    home=/srv/midwife-emr
    shell=/bin/bash
