---
- name: Add support group
  group: name=admin state=present
- name: Add support user
  user:
    name="{{ support_user }}"
    password="{{ support_user_password }}"
    comment="Midwife-EMR support user."
    group=admin
    state=present
    createhome=yes
    shell=/bin/bash

- name: Install the SSH public key for support user
  authorized_key:
    user: "{{ support_user }}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file', 'roles/preparation/files/support_user.pub') }}"

- name: Change the root password
  user:
    name=root
    password="{{ root_password }}"
    state=present

- name: Install new sshd_config file.
  template:
    src: roles/preparation/files/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify: restart ssh
