---
- name: Install Ubuntu packages
  apt:
    name="{{ item }}"
    state=present
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - debconf
    - debconf-utils
    - fail2ban
    - mysql-server
    - nginx-light
    - ufw

