---
- name: Install Ubuntu packages
  apt:
    name="{{ item }}"
    state=present
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - automysqlbackup
    - debconf
    - debconf-utils
    - dnsmasq
    - fail2ban
    - git-core
    - hostapd
    - iptables
    - isc-dhcp-server
    - libnl-3-dev
    - libnl-genl-3-dev
    - libssl-dev
    - locales
    - mariadb-server-10.0
    - mariadb-client-10.0
    - nginx
    - pkg-config
    - python-mysqldb
    - rfkill
    - unattended-upgrades
    - vim
    - exfat-fuse
    - exfat-utils

- name: Upgrade packages safely during Ansible run
  apt:
    upgrade: safe

- name: Change password of all MySQL root user accounts
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    state: present
    host_all: yes

- name: Write out the MySQL root password so Ansible can find it
  blockinfile:
    block: |
      [client]
      user=root
      password="{{ mysql_root_password }}"
    create: yes
    dest: /root/.my.cnf
    insertafter: EOF
    state: present
    owner: root
    group: root
    mode: "u=rw,go="

- name: Disable plugins for the root user which allow password-less access.
  command: /usr/bin/mysql -uroot -e "UPDATE mysql.user SET plugin='' WHERE User='root';FLUSH PRIVILEGES;" mysql
