---
- name: Add the Nginx PPA to the repository list
  apt_repository: repo='ppa:nginx/stable'

- name: Install Ubuntu packages
  apt:
    name="{{ item }}"
    state=present
    update_cache=yes
    cache_valid_time=86400
  with_items:
    - debconf
    - debconf-utils
    - fail2ban
    - mysql-server
    - nginx
    - ufw
    - iptables
    - isc-dhcp-server
    - python-mysqldb
    - automysqlbackup
    - unattended-upgrades
    - locales

- name: Upgrade the initscripts package forcing the use of the new ondemand script
  apt:
    name: initscripts
    state: latest
    dpkg_options: 'force-confnew,force-confdef'

- name: Upgrade packages safely during Ansible run
  apt:
    upgrade: safe

- name: Change password of all MySQL root user accounts
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    state: present
    host_all: yes

- name: Write out the MySQL root password so Ansible can find it
  blockinfile:
    block: |
      [client]
      user=root
      password={{ mysql_root_password }}
    create: yes
    dest: /root/.my.cnf
    insertafter: EOF
    state: present
    owner: root
    group: root
    mode: "u=rw,go="

