---
# Playbook: build_odroid
- name: Setup Midwife-EMR on the ODroid
  hosts: all
  become: yes
  gather_facts: True
  vars_files:
    - secure.yaml
  roles:
    - services
    - time
    - misc
    - nodejs
    - users
    - shutdown
    - network
    - midwife-emr-tls
    - build_clients
    - midwife-emr
    - midwife-emr-internal
    - backups
    - autossh
