---
# Playbook: build_odroid
- name: Setup Midwife-EMR on the ODroid
  hosts: all
  remote_user: root
  gather_facts: True
  vars_files:
    - secure.yaml
  vars_prompt:
    - name: "midwife_emr_support_forwarding_port"
      prompt: "Enter the port on the remote support server for Midwife-EMR-Support to port-forward."
      private: no
  roles:
    - services
    - time
    - misc
    - nodejs
    - users
    - shutdown
    - network
    - midwife-emr-tls
    - midwife-emr
    - midwife-emr-internal
    - backups
    - autossh
