---

- name: Create Midwife-EMR-TLS directories
  file:
    dest: /srv/midwife-emr-tls/pki/
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Install Midwife-EMR-TLS CA config file
  copy:
    src: roles/midwife-emr-tls/files/ca.conf
    dest: /srv/midwife-emr-tls/pki/
    owner: root
    group: root
    mode: "u=rw,go="

- name: Install Midwife-EMR-TLS Server config file
  copy:
    src: roles/midwife-emr-tls/files/servercsr.conf
    dest: /srv/midwife-emr-tls/pki/
    owner: root
    group: root
    mode: "u=rw,go="

- name: Install Midwife-EMR-TLS command file
  copy:
    src: roles/midwife-emr-tls/files/manage-midwife-emr-tls
    dest: /srv/midwife-emr-tls/pki/
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Create a password for the CA
  shell: openssl rand 20|openssl base64
  args:
    creates: /srv/midwife-emr-tls/pki/capw.txt
  register: ca_password

- name: Save the password for the CA
  shell: echo "{{ ca_password.stdout }}" > /srv/midwife-emr-tls/pki/capw.txt
  when: ca_password.changed == true
  register: ca_password_saved

- name: Set permissions on the password file
  file:
    path: /srv/midwife-emr-tls/pki/capw.txt
    owner: root
    group: root
    mode: "u=rw,go="

- name: Create the directory for TLS certificates/keys for Nginx
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go="

- name: Install the midwife-emr-tls service.
  copy:
    src: roles/midwife-emr-tls/files/midwife-emr-tls.service
    dest: /etc/systemd/system/midwife-emr-tls.service
    owner: root
    group: root
    mode: "u=rw,go=r"
  register: midwife_emr_tls_installed

- name: Reload the systemd services as necessary
  command: systemctl daemon-reload
  when: midwife_emr_tls_installed is defined and midwife_emr_tls_installed.changed == True

- name: Enable the midwife-emr-tls service
  command: systemctl enable midwife-emr-tls.service
